// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqaUSEsuLJdtB6smaZoXnnJBnabsM1im0',
    appId: '1:1093615283192:web:25d93fb7ecdcdb390f040d',
    messagingSenderId: '1093615283192',
    projectId: 'portfolio-72d89',
    authDomain: 'portfolio-72d89.firebaseapp.com',
    storageBucket: 'portfolio-72d89.appspot.com',
    measurementId: 'G-3M8HYPZX6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8mYc1SniwqEREmb-tJ3bTl07te3jvKU',
    appId: '1:1093615283192:android:bdccd7b5253bc3370f040d',
    messagingSenderId: '1093615283192',
    projectId: 'portfolio-72d89',
    storageBucket: 'portfolio-72d89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_pRvnUl8nKC4QLnJ6AyGfsQpoIonan7E',
    appId: '1:1093615283192:ios:78c4f12bb5a4c4bf0f040d',
    messagingSenderId: '1093615283192',
    projectId: 'portfolio-72d89',
    storageBucket: 'portfolio-72d89.appspot.com',
    iosBundleId: 'com.example.webapp',
  );
}
